name: Build OpenWrt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get -y update
          sudo -E apt-get -y install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python3-distutils python3-setuptools rsync subversion swig time xsltproc zlib1g-dev 
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get -y clean
          df -h
          
      - name: Clone source code
        run: |
          git clone https://github.com/openwrt/openwrt
          
      - name: Load custom feeds
        run: |
          cd openwrt
          echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> feeds.conf.default
          echo "src-git small https://github.com/kenzok8/small" >> feeds.conf.default
          cat feeds.conf.default
          
      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a
        
      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a
        
      - name: Make menuconfig
        uses: P3TERX/ssh2actions@main
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
      - name: Compile the firmware
        run: cd openwrt && make V=s
        
      - name: Prepare artifact
        run: | 
          mkdir -p ./artifact/firmware
          cp -rf $(find ./openwrt/bin/targets/ -type f) ./artifact/firmware/
          
      - name: Upload firmware
        run: |
          curl -sL https://git.io/cowtransfer | sh 
          ./cowtransfer-uploader ./artifact/firmware
       
